[package]
name = "client"
version = "0.1.7"
edition = "2024"
autobins = false

[lib]
name = "client"

[[bin]]
name = "lfp-pipe-client"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
atomic-write-file.workspace = true
async-nats.workspace = true
base64.workspace = true
futures.workspace = true
httparse.workspace = true
jsonwebtoken.workspace = true
reqwest.workspace = true
rustls.workspace = true
rustls-acme.workspace = true
serde.workspace = true
serde_json.workspace = true
shared = { path = "../shared" }
tokio.workspace = true
tokio-stream.workspace = true
tracing.workspace = true

[target.'cfg(any(target_os = "windows", target_os = "macos", target_os = "linux"))'.dependencies]
open.workspace = true
tray-icon.workspace = true
winit.workspace = true
