[package]
name = "client"
version = "0.1.2"
edition = "2024"
autobins = false

[lib]
name = "client"

[[bin]]
name = "lfp-pipe-client"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
async-nats.workspace = true
base64.workspace = true
futures.workspace = true
reqwest.workspace = true
rustls.workspace = true
serde.workspace = true
serde_json.workspace = true
shared = { path = "../shared" }
tokio.workspace = true
tracing.workspace = true
