//! Fail-closed JWT authorization for HTTP backends.

use std::{
    collections::hash_map::DefaultHasher,
    fs,
    hash::{Hash, Hasher},
    io::Write,
    path::Path,
    str::FromStr,
    sync::Arc,
    time::{Duration, Instant, SystemTime, UNIX_EPOCH},
};

use anyhow::{Context, anyhow, bail, ensure};
use atomic_write_file::AtomicWriteFile;
use base64::{Engine, engine::general_purpose::URL_SAFE_NO_PAD};
use bytes::Bytes;
use constant_time_eq::constant_time_eq;
use cookie::{Cookie, CookieJar, Key, SameSite};
use hyper::{HeaderMap, Method, StatusCode, Uri, header};
use jsonwebtoken::{
    Algorithm, DecodingKey, Validation, decode, decode_header,
    jwk::{JwkSet, PublicKeyUse},
};
use openidconnect::{
    AccessTokenHash, AuthorizationCode, ClientId, ClientSecret, CsrfToken, IssuerUrl, Nonce,
    OAuth2TokenResponse, PkceCodeChallenge, PkceCodeVerifier, RedirectUrl, Scope, TokenResponse,
    core::{CoreAuthenticationFlow, CoreClient, CoreProviderMetadata},
};
use reqwest::Client;
use serde::{Deserialize, Serialize};
use serde_json::Value;
use shared::config::{ClientAuthorizationConfig, RoleMatch};
use tokio::sync::{Mutex, RwLock};
use tracing::{debug, warn};

#[derive(Debug, Deserialize)]
struct DiscoveryDocument {
    issuer: String,
    jwks_uri: String,
}

/// Authentication facts forwarded only after credentials have been verified.
#[derive(Clone, Debug, Deserialize, Serialize)]
pub(crate) struct AuthenticatedIdentity {
    pub(crate) subject: String,
    pub(crate) username: String,
    #[serde(default)]
    pub(crate) name: Option<String>,
    pub(crate) email: Option<String>,
    pub(crate) groups: Vec<String>,
    pub(crate) expires_unix: u64,
}

/// A complete response generated by the forward-auth layer.
pub(crate) struct AuthResponse {
    pub(crate) status: StatusCode,
    pub(crate) headers: HeaderMap,
    pub(crate) body: Bytes,
}

/// Result of applying bearer and browser-session authorization to one request.
pub(crate) enum AuthorizationDecision {
    Allow(Option<AuthenticatedIdentity>),
    Respond(AuthResponse),
}

#[derive(Clone)]
pub(crate) struct Authorizer {
    config: Arc<ClientAuthorizationConfig>,
    bearer: Option<JwtAuthorizer>,
    oidc: Option<OidcAuthorizer>,
}

#[derive(Clone)]
struct OidcAuthorizer {
    config: Arc<ClientAuthorizationConfig>,
    hostname: Arc<String>,
    provider: CoreProviderMetadata,
    client_secret: Arc<Option<String>>,
    http: openidconnect::reqwest::Client,
    cookie_key: Key,
    flow_cookie: Arc<String>,
    session_cookie: Arc<String>,
}

#[derive(Debug, Deserialize, Serialize)]
struct OidcFlow {
    state: String,
    nonce: String,
    pkce_verifier: String,
    return_to: String,
    expires_unix: u64,
}

impl Authorizer {
    pub(crate) async fn load(
        config: ClientAuthorizationConfig,
        hostname: &str,
    ) -> anyhow::Result<Self> {
        let config = Arc::new(config);
        let bearer = if config.bearer_enabled() {
            Some(JwtAuthorizer::load((*config).clone()).await?)
        } else {
            None
        };
        let oidc = if config.oidc_enabled() {
            Some(OidcAuthorizer::load(config.clone(), hostname).await?)
        } else {
            None
        };
        Ok(Self {
            config,
            bearer,
            oidc,
        })
    }

    pub(crate) fn forward_authorization(&self) -> bool {
        self.config.forward_authorization
    }

    pub(crate) fn request_limits(&self) -> (usize, Duration) {
        (
            self.config.max_header_bytes,
            Duration::from_millis(self.config.header_timeout_ms),
        )
    }

    pub(crate) fn handles_endpoint(&self, path: &str) -> bool {
        self.oidc.is_some()
            && (path == self.config.oidc_callback_path || path == self.config.oidc_logout_path)
    }

    pub(crate) async fn authorize(
        &self,
        method: &Method,
        uri: &Uri,
        headers: &HeaderMap,
    ) -> AuthorizationDecision {
        if let Some(oidc) = &self.oidc {
            if uri.path() == self.config.oidc_callback_path {
                return AuthorizationDecision::Respond(oidc.callback(method, uri, headers).await);
            }
            if uri.path() == self.config.oidc_logout_path {
                return AuthorizationDecision::Respond(oidc.logout(method));
            }
        }

        if headers.contains_key(header::AUTHORIZATION) {
            let Some(bearer) = &self.bearer else {
                return AuthorizationDecision::Respond(unauthorized_response());
            };
            return match bearer.authorize_headers(headers).await {
                Ok(claims) => AuthorizationDecision::Allow(
                    identity_from_claims(&claims, &self.config.roles_claim).ok(),
                ),
                Err(Denial::Forbidden(_)) => AuthorizationDecision::Respond(forbidden_response()),
                Err(Denial::Unauthorized(_)) => {
                    AuthorizationDecision::Respond(unauthorized_response())
                }
            };
        }

        if let Some(oidc) = &self.oidc {
            return match oidc.session(headers) {
                Ok(Some(identity)) => AuthorizationDecision::Allow(Some(identity)),
                Ok(None) | Err(_) => AuthorizationDecision::Respond(oidc.login(uri)),
            };
        }

        AuthorizationDecision::Respond(unauthorized_response())
    }
}

impl OidcAuthorizer {
    async fn load(config: Arc<ClientAuthorizationConfig>, hostname: &str) -> anyhow::Result<Self> {
        let client_secret = if let Some(path) = config
            .oidc_client_secret_file
            .as_deref()
            .filter(|path| !path.trim().is_empty())
        {
            let secret_path = crate::paths::expand_home(path)?;
            let secret = fs::read_to_string(&secret_path)
                .with_context(|| format!("read OIDC client secret {}", secret_path.display()))?
                .trim()
                .to_string();
            ensure!(!secret.is_empty(), "OIDC client secret file is empty");
            Some(secret)
        } else {
            None
        };

        let http = openidconnect::reqwest::ClientBuilder::new()
            .redirect(openidconnect::reqwest::redirect::Policy::none())
            .timeout(Duration::from_secs(10))
            .build()
            .context("construct OIDC HTTP client")?;
        let provider = CoreProviderMetadata::discover_async(
            IssuerUrl::new(config.issuer.clone()).context("parse OIDC issuer")?,
            &http,
        )
        .await
        .context("discover OIDC provider")?;
        ensure!(
            provider.issuer().as_str() == config.issuer,
            "OIDC discovery issuer does not exactly match configuration"
        );

        let key_path = crate::paths::expand_home(&config.oidc_session_key_file)?;
        let cookie_key = load_or_create_cookie_key(&key_path)?;
        let mut hasher = DefaultHasher::new();
        config.issuer.hash(&mut hasher);
        config.oidc_client_id.hash(&mut hasher);
        hostname.hash(&mut hasher);
        let namespace = format!("{:016x}", hasher.finish());

        Ok(Self {
            config,
            hostname: Arc::new(hostname.to_string()),
            provider,
            client_secret: Arc::new(client_secret),
            http,
            cookie_key,
            flow_cookie: Arc::new(format!("__Host-lfp_flow_{namespace}")),
            session_cookie: Arc::new(format!("__Host-lfp_session_{namespace}")),
        })
    }

    fn client(
        &self,
    ) -> anyhow::Result<
        CoreClient<
            openidconnect::EndpointSet,
            openidconnect::EndpointNotSet,
            openidconnect::EndpointNotSet,
            openidconnect::EndpointNotSet,
            openidconnect::EndpointMaybeSet,
            openidconnect::EndpointMaybeSet,
        >,
    > {
        let redirect = format!(
            "https://{}{}",
            self.hostname, self.config.oidc_callback_path
        );
        Ok(CoreClient::from_provider_metadata(
            self.provider.clone(),
            ClientId::new(
                self.config
                    .oidc_client_id
                    .clone()
                    .context("OIDC client ID is missing")?,
            ),
            self.client_secret
                .as_ref()
                .as_ref()
                .map(|secret| ClientSecret::new(secret.clone())),
        )
        .set_redirect_uri(RedirectUrl::new(redirect).context("parse OIDC redirect URL")?))
    }

    fn login(&self, uri: &Uri) -> AuthResponse {
        match self.login_inner(uri) {
            Ok(response) => response,
            Err(error) => {
                warn!(?error, "failed to begin OIDC login");
                internal_error_response()
            }
        }
    }

    fn login_inner(&self, uri: &Uri) -> anyhow::Result<AuthResponse> {
        let client = self.client()?;
        let (pkce_challenge, pkce_verifier) = PkceCodeChallenge::new_random_sha256();
        let mut request = client.authorize_url(
            CoreAuthenticationFlow::AuthorizationCode,
            CsrfToken::new_random,
            Nonce::new_random,
        );
        for scope in self
            .config
            .oidc_scopes
            .iter()
            .filter(|scope| !scope.eq_ignore_ascii_case("openid"))
        {
            request = request.add_scope(Scope::new(scope.clone()));
        }
        let (url, state, nonce) = request.set_pkce_challenge(pkce_challenge).url();
        let return_to = safe_return_to(uri);
        let flow = OidcFlow {
            state: state.secret().clone(),
            nonce: nonce.secret().clone(),
            pkce_verifier: pkce_verifier.secret().clone(),
            return_to,
            expires_unix: unix_now().saturating_add(10 * 60),
        };
        let cookie = self.encrypt_cookie(&self.flow_cookie, &flow, 10 * 60)?;
        redirect_response(StatusCode::FOUND, url.as_str(), [cookie])
    }

    async fn callback(&self, method: &Method, uri: &Uri, headers: &HeaderMap) -> AuthResponse {
        if method != Method::GET {
            return method_not_allowed_response();
        }
        match self.callback_inner(uri, headers).await {
            Ok(response) => response,
            Err(error) => {
                warn!(?error, "OIDC callback rejected");
                unauthorized_response()
            }
        }
    }

    async fn callback_inner(&self, uri: &Uri, headers: &HeaderMap) -> anyhow::Result<AuthResponse> {
        let flow: OidcFlow = self
            .decrypt_cookie(headers, &self.flow_cookie)?
            .context("OIDC flow cookie is missing or invalid")?;
        ensure!(flow.expires_unix > unix_now(), "OIDC flow expired");
        let query = uri.query().context("OIDC callback query is missing")?;
        let params: std::collections::HashMap<String, String> =
            url::form_urlencoded::parse(query.as_bytes())
                .into_owned()
                .collect();
        ensure!(
            !params.contains_key("error"),
            "OIDC provider returned an error"
        );
        let state = params.get("state").context("OIDC state is missing")?;
        ensure!(
            constant_time_eq(state.as_bytes(), flow.state.as_bytes()),
            "OIDC state does not match"
        );
        let code = params.get("code").context("OIDC code is missing")?;

        let client = self.client()?;
        let token_response = client
            .exchange_code(AuthorizationCode::new(code.clone()))
            .context("OIDC provider has no token endpoint")?
            .set_pkce_verifier(PkceCodeVerifier::new(flow.pkce_verifier))
            .request_async(&self.http)
            .await
            .context("exchange OIDC authorization code")?;
        let id_token = token_response
            .id_token()
            .context("OIDC response has no ID token")?;
        let verifier = client.id_token_verifier();
        let claims = id_token
            .claims(&verifier, &Nonce::new(flow.nonce))
            .context("verify OIDC ID token")?;
        if let Some(expected) = claims.access_token_hash() {
            let actual = AccessTokenHash::from_token(
                token_response.access_token(),
                id_token
                    .signing_alg()
                    .context("read ID token signing algorithm")?,
                id_token
                    .signing_key(&verifier)
                    .context("read ID token signing key")?,
            )
            .context("calculate OIDC access-token hash")?;
            ensure!(&actual == expected, "OIDC access-token hash does not match");
        }

        let raw_claims = decode_verified_claims(&id_token.to_string())?;
        validate_roles(&raw_claims, &self.config).map_err(|denial| match denial {
            Denial::Unauthorized(error) | Denial::Forbidden(error) => error,
        })?;
        let mut identity = identity_from_claims(&raw_claims, &self.config.roles_claim)?;
        identity.expires_unix = unix_now().saturating_add(self.config.oidc_session_ttl_seconds);
        let session = self.encrypt_cookie(
            &self.session_cookie,
            &identity,
            self.config.oidc_session_ttl_seconds,
        )?;
        let clear_flow = clear_cookie(&self.flow_cookie);
        redirect_response(
            StatusCode::SEE_OTHER,
            &flow.return_to,
            [session, clear_flow],
        )
    }

    fn logout(&self, method: &Method) -> AuthResponse {
        if method != Method::GET && method != Method::POST {
            return method_not_allowed_response();
        }
        redirect_response(
            StatusCode::SEE_OTHER,
            "/",
            [
                clear_cookie(&self.session_cookie),
                clear_cookie(&self.flow_cookie),
            ],
        )
        .unwrap_or_else(|_| internal_error_response())
    }

    fn session(&self, headers: &HeaderMap) -> anyhow::Result<Option<AuthenticatedIdentity>> {
        let identity: Option<AuthenticatedIdentity> =
            self.decrypt_cookie(headers, &self.session_cookie)?;
        let Some(identity) = identity else {
            return Ok(None);
        };
        if identity.expires_unix <= unix_now() {
            return Ok(None);
        }
        Ok(Some(identity))
    }

    fn encrypt_cookie<T: Serialize>(
        &self,
        name: &str,
        value: &T,
        max_age_seconds: u64,
    ) -> anyhow::Result<String> {
        let encoded = URL_SAFE_NO_PAD.encode(serde_json::to_vec(value)?);
        let cookie = Cookie::build((name.to_string(), encoded))
            .path("/")
            .secure(true)
            .http_only(true)
            .same_site(SameSite::Lax)
            .max_age(cookie::time::Duration::seconds(
                i64::try_from(max_age_seconds).unwrap_or(i64::MAX),
            ))
            .build();
        let mut jar = CookieJar::new();
        jar.private_mut(&self.cookie_key).add(cookie);
        let output = jar
            .get(name)
            .context("encrypted cookie was not created")?
            .to_string();
        ensure!(
            output.len() <= 4096,
            "encrypted OIDC cookie exceeds 4096 bytes"
        );
        Ok(output)
    }

    fn decrypt_cookie<T: for<'de> Deserialize<'de>>(
        &self,
        headers: &HeaderMap,
        name: &str,
    ) -> anyhow::Result<Option<T>> {
        let Some(raw) = request_cookie(headers, name) else {
            return Ok(None);
        };
        let mut jar = CookieJar::new();
        jar.add_original(Cookie::new(name.to_string(), raw));
        let Some(cookie) = jar.private(&self.cookie_key).get(name) else {
            return Ok(None);
        };
        let decoded = URL_SAFE_NO_PAD
            .decode(cookie.value())
            .context("decode encrypted cookie")?;
        Ok(Some(
            serde_json::from_slice(&decoded).context("decode OIDC cookie payload")?,
        ))
    }
}

#[derive(Clone)]
pub(crate) struct JwtAuthorizer {
    config: Arc<ClientAuthorizationConfig>,
    algorithms: Arc<Vec<Algorithm>>,
    http: Client,
    keys: Arc<RwLock<KeyState>>,
    refresh: Arc<Mutex<Instant>>,
}

struct KeyState {
    set: JwkSet,
    obtained_at: SystemTime,
}

#[derive(Debug)]
pub(crate) enum Denial {
    Unauthorized(anyhow::Error),
    Forbidden(anyhow::Error),
}

impl JwtAuthorizer {
    pub(crate) async fn load(config: ClientAuthorizationConfig) -> anyhow::Result<Self> {
        let mut config = config;
        config.jwks_cache_file = crate::paths::expand_home(&config.jwks_cache_file)?
            .to_string_lossy()
            .into_owned();
        let algorithms = config
            .algorithms
            .iter()
            .map(|value| parse_algorithm(value))
            .collect::<anyhow::Result<Vec<_>>>()?;
        ensure!(
            !algorithms.is_empty(),
            "JWT algorithm allowlist cannot be empty"
        );
        let http = Client::builder()
            .timeout(Duration::from_secs(10))
            .build()
            .context("construct JWT key HTTP client")?;

        let remote = fetch_jwks(&http, &config).await;
        let state = match remote {
            Ok(set) => {
                persist_jwks(Path::new(&config.jwks_cache_file), &set)?;
                KeyState {
                    set,
                    obtained_at: SystemTime::now(),
                }
            }
            Err(remote_error) => {
                let cached = load_cached_jwks(&config).with_context(|| {
                    format!("identity provider unavailable ({remote_error:#}) and JWKS cache is unusable")
                })?;
                warn!(?remote_error, cache = %config.jwks_cache_file, "using cached JWKS");
                cached
            }
        };

        Ok(Self {
            config: Arc::new(config),
            algorithms: Arc::new(algorithms),
            http,
            keys: Arc::new(RwLock::new(state)),
            refresh: Arc::new(Mutex::new(Instant::now())),
        })
    }

    async fn authorize_headers(&self, headers: &HeaderMap) -> Result<Value, Denial> {
        let value = headers
            .get(header::AUTHORIZATION)
            .ok_or_else(|| Denial::Unauthorized(anyhow!("Authorization header is required")))?
            .to_str()
            .map_err(|error| {
                Denial::Unauthorized(anyhow!("Authorization header is invalid: {error}"))
            })?;
        let (scheme, token) = value
            .trim()
            .split_once(' ')
            .ok_or_else(|| Denial::Unauthorized(anyhow!("Authorization header must use Bearer")))?;
        if !scheme.eq_ignore_ascii_case("Bearer") || token.trim().is_empty() {
            return Err(Denial::Unauthorized(anyhow!(
                "Authorization header must use Bearer"
            )));
        }
        self.authorize_token(token.trim()).await
    }

    async fn authorize_token(&self, token: &str) -> Result<Value, Denial> {
        self.refresh_if_due(false)
            .await
            .map_err(Denial::Unauthorized)?;
        let header = decode_header(token)
            .map_err(|error| Denial::Unauthorized(anyhow!("invalid JWT header: {error}")))?;
        if !self.algorithms.contains(&header.alg) {
            return Err(Denial::Unauthorized(anyhow!(
                "JWT algorithm is not allowed"
            )));
        }
        let kid = header
            .kid
            .as_deref()
            .ok_or_else(|| Denial::Unauthorized(anyhow!("JWT header is missing kid")))?;

        let mut key = self.key_for(kid, header.alg).await;
        if key.is_err() {
            self.refresh_if_due(true)
                .await
                .map_err(Denial::Unauthorized)?;
            key = self.key_for(kid, header.alg).await;
        }
        let key = key.map_err(Denial::Unauthorized)?;
        let mut validation = Validation::new(header.alg);
        validation.leeway = self.config.leeway_seconds;
        validation.validate_nbf = true;
        validation.set_issuer(&[&self.config.issuer]);
        validation.set_audience(&self.config.audiences);
        validation.set_required_spec_claims(&["exp", "iss", "aud"]);
        let claims = decode::<Value>(token, &key, &validation)
            .map_err(|error| Denial::Unauthorized(anyhow!("JWT validation failed: {error}")))?
            .claims;
        validate_roles(&claims, &self.config)?;
        Ok(claims)
    }

    async fn key_for(&self, kid: &str, algorithm: Algorithm) -> anyhow::Result<DecodingKey> {
        let state = self.keys.read().await;
        ensure_cache_age(&self.config, state.obtained_at)?;
        let jwk = state
            .set
            .find(kid)
            .ok_or_else(|| anyhow!("JWT signing key was not found"))?;
        if let Some(usage) = &jwk.common.public_key_use {
            ensure!(
                *usage == PublicKeyUse::Signature,
                "JWK is not a signing key"
            );
        }
        if let Some(key_algorithm) = jwk.common.key_algorithm {
            ensure!(
                Algorithm::try_from(key_algorithm).ok() == Some(algorithm),
                "JWK algorithm does not match JWT header"
            );
        }
        DecodingKey::from_jwk(jwk).context("construct JWT verification key")
    }

    async fn refresh_if_due(&self, force: bool) -> anyhow::Result<()> {
        let mut last_attempt = self.refresh.lock().await;
        let minimum_interval = if force {
            Duration::from_secs(10)
        } else {
            Duration::from_secs(self.config.jwks_refresh_seconds)
        };
        if last_attempt.elapsed() < minimum_interval {
            return Ok(());
        }
        *last_attempt = Instant::now();
        match fetch_jwks(&self.http, &self.config).await {
            Ok(set) => {
                persist_jwks(Path::new(&self.config.jwks_cache_file), &set)?;
                *self.keys.write().await = KeyState {
                    set,
                    obtained_at: SystemTime::now(),
                };
                debug!("refreshed JWT verification keys");
                Ok(())
            }
            Err(error) => {
                let obtained_at = self.keys.read().await.obtained_at;
                ensure_cache_age(&self.config, obtained_at)?;
                warn!(?error, "JWKS refresh failed; retaining cached keys");
                Ok(())
            }
        }
    }
}

async fn fetch_jwks(http: &Client, config: &ClientAuthorizationConfig) -> anyhow::Result<JwkSet> {
    let jwks_uri = if let Some(uri) = &config.jwks_uri {
        uri.clone()
    } else {
        let discovery_uri = format!(
            "{}/.well-known/openid-configuration",
            config.issuer.trim_end_matches('/')
        );
        let discovery = http
            .get(discovery_uri)
            .send()
            .await
            .context("fetch OIDC discovery document")?
            .error_for_status()
            .context("OIDC discovery endpoint returned an error")?
            .json::<DiscoveryDocument>()
            .await
            .context("decode OIDC discovery document")?;
        ensure!(
            discovery.issuer == config.issuer,
            "OIDC discovery issuer does not exactly match configuration"
        );
        discovery.jwks_uri
    };
    let set = http
        .get(jwks_uri)
        .send()
        .await
        .context("fetch JWKS")?
        .error_for_status()
        .context("JWKS endpoint returned an error")?
        .json::<JwkSet>()
        .await
        .context("decode JWKS")?;
    ensure!(!set.keys.is_empty(), "JWKS contains no keys");
    Ok(set)
}

fn load_cached_jwks(config: &ClientAuthorizationConfig) -> anyhow::Result<KeyState> {
    let path = Path::new(&config.jwks_cache_file);
    let metadata = fs::metadata(path)
        .with_context(|| format!("read JWKS cache metadata {}", path.display()))?;
    let obtained_at = metadata
        .modified()
        .context("read JWKS cache modification time")?;
    ensure_cache_age(config, obtained_at)?;
    let bytes = fs::read(path).with_context(|| format!("read JWKS cache {}", path.display()))?;
    let set: JwkSet = serde_json::from_slice(&bytes).context("decode cached JWKS")?;
    ensure!(!set.keys.is_empty(), "cached JWKS contains no keys");
    Ok(KeyState { set, obtained_at })
}

fn ensure_cache_age(
    config: &ClientAuthorizationConfig,
    obtained_at: SystemTime,
) -> anyhow::Result<()> {
    if config.jwks_max_stale_seconds == 0 {
        return Ok(());
    }
    let age = SystemTime::now()
        .duration_since(obtained_at)
        .unwrap_or_default();
    ensure!(
        age <= Duration::from_secs(config.jwks_max_stale_seconds),
        "cached JWKS exceeds jwks_max_stale_seconds"
    );
    Ok(())
}

fn persist_jwks(path: &Path, set: &JwkSet) -> anyhow::Result<()> {
    let parent = path.parent().filter(|value| !value.as_os_str().is_empty());
    if let Some(parent) = parent {
        fs::create_dir_all(parent)
            .with_context(|| format!("create JWKS cache directory {}", parent.display()))?;
    }
    let bytes = serde_json::to_vec(set).context("encode JWKS cache")?;
    let mut file = AtomicWriteFile::open(path)
        .with_context(|| format!("open atomic JWKS cache {}", path.display()))?;
    file.write_all(&bytes)
        .with_context(|| format!("write JWKS cache {}", path.display()))?;
    file.commit()
        .with_context(|| format!("replace JWKS cache {}", path.display()))?;
    Ok(())
}

fn parse_algorithm(value: &str) -> anyhow::Result<Algorithm> {
    let algorithm =
        Algorithm::from_str(value).with_context(|| format!("unsupported JWT algorithm {value}"))?;
    ensure!(
        !matches!(
            algorithm,
            Algorithm::HS256 | Algorithm::HS384 | Algorithm::HS512
        ),
        "symmetric JWT algorithms are not accepted for JWKS authorization"
    );
    Ok(algorithm)
}

#[cfg(test)]
const MAX_HTTP_HEADERS: usize = 128;

#[cfg(test)]
pub(crate) fn request_path(bytes: &[u8]) -> anyhow::Result<&str> {
    let mut headers = [httparse::EMPTY_HEADER; MAX_HTTP_HEADERS];
    let mut request = httparse::Request::new(&mut headers);
    ensure!(
        request
            .parse(bytes)
            .context("parse HTTP request")?
            .is_complete(),
        "incomplete HTTP request headers"
    );
    let target = request
        .path
        .ok_or_else(|| anyhow!("HTTP request target is missing"))?;
    let path = target.split('?').next().unwrap_or(target);
    ensure!(
        path.starts_with('/'),
        "HTTP request target must use origin form"
    );
    Ok(path)
}

#[cfg(test)]
pub(crate) fn strip_request_path_prefix(bytes: Vec<u8>, prefix: &str) -> anyhow::Result<Vec<u8>> {
    let line_end = bytes
        .windows(2)
        .position(|window| window == b"\r\n")
        .ok_or_else(|| anyhow!("HTTP request line is incomplete"))?;
    let request_line =
        std::str::from_utf8(&bytes[..line_end]).context("HTTP request line is not UTF-8")?;
    let first_space = request_line
        .find(' ')
        .ok_or_else(|| anyhow!("HTTP method is malformed"))?;
    let target_start = first_space + 1;
    let target_end = request_line[target_start..]
        .find(' ')
        .map(|offset| target_start + offset)
        .ok_or_else(|| anyhow!("HTTP request target is malformed"))?;
    let target = &request_line[target_start..target_end];
    let query_start = target.find('?').unwrap_or(target.len());
    let path = &target[..query_start];
    let prefix = prefix.trim_end_matches('/');
    let remainder = path
        .strip_prefix(prefix)
        .filter(|value| value.is_empty() || value.starts_with('/'))
        .ok_or_else(|| anyhow!("HTTP request path does not match configured prefix"))?;
    let rewritten_path = if remainder.is_empty() { "/" } else { remainder };
    let mut output = Vec::with_capacity(bytes.len());
    output.extend_from_slice(&bytes[..target_start]);
    output.extend_from_slice(rewritten_path.as_bytes());
    output.extend_from_slice(&target.as_bytes()[query_start..]);
    output.extend_from_slice(&bytes[target_end..]);
    Ok(output)
}

#[cfg(test)]
pub(crate) fn set_host_header(bytes: Vec<u8>, host: &str) -> anyhow::Result<Vec<u8>> {
    ensure!(
        !host.is_empty() && !host.contains(['\r', '\n']),
        "backend_host must be a non-empty HTTP Host value"
    );
    let header_end = bytes
        .windows(4)
        .position(|window| window == b"\r\n\r\n")
        .ok_or_else(|| anyhow!("incomplete HTTP request headers"))?;
    let mut output = Vec::with_capacity(bytes.len() + host.len());
    let mut host_count = 0;
    for (index, line) in bytes[..header_end].split(|byte| *byte == b'\n').enumerate() {
        let line = line.strip_suffix(b"\r").unwrap_or(line);
        let is_host = index > 0
            && line
                .splitn(2, |byte| *byte == b':')
                .next()
                .is_some_and(|name| name.eq_ignore_ascii_case(b"host"));
        if is_host {
            host_count += 1;
            output.extend_from_slice(b"Host: ");
            output.extend_from_slice(host.as_bytes());
        } else {
            output.extend_from_slice(line);
        }
        output.extend_from_slice(b"\r\n");
    }
    ensure!(
        host_count == 1,
        "HTTP request must contain exactly one Host header"
    );
    output.extend_from_slice(b"\r\n");
    output.extend_from_slice(&bytes[header_end + 4..]);
    Ok(output)
}

/// Apply standard reverse-proxy headers using trusted tunnel metadata.
#[cfg(test)]
pub(crate) fn set_proxy_headers(
    bytes: Vec<u8>,
    client_ip: Option<&str>,
    scheme: &str,
) -> anyhow::Result<Vec<u8>> {
    ensure!(
        matches!(scheme, "http" | "https"),
        "forwarded scheme must be http or https"
    );
    let header_end = bytes
        .windows(4)
        .position(|window| window == b"\r\n\r\n")
        .ok_or_else(|| anyhow!("incomplete HTTP request headers"))?;
    let mut output = Vec::with_capacity(bytes.len() + 160);
    let mut original_host = None;
    let mut has_accept_encoding = false;

    for (index, line) in bytes[..header_end].split(|byte| *byte == b'\n').enumerate() {
        let line = line.strip_suffix(b"\r").unwrap_or(line);
        if index == 0 {
            output.extend_from_slice(line);
            output.extend_from_slice(b"\r\n");
            continue;
        }
        let Some(separator) = line.iter().position(|byte| *byte == b':') else {
            continue;
        };
        let name = &line[..separator];
        let value = line[separator + 1..]
            .strip_prefix(b" ")
            .unwrap_or(&line[separator + 1..]);
        if name.eq_ignore_ascii_case(b"host") {
            ensure!(
                original_host.is_none(),
                "HTTP request must contain exactly one Host header"
            );
            original_host = Some(value.to_vec());
        }
        if name.eq_ignore_ascii_case(b"accept-encoding") {
            has_accept_encoding = true;
        }
        if name.eq_ignore_ascii_case(b"x-forwarded-for")
            || name.eq_ignore_ascii_case(b"x-forwarded-proto")
            || name.eq_ignore_ascii_case(b"x-forwarded-host")
        {
            continue;
        }
        output.extend_from_slice(line);
        output.extend_from_slice(b"\r\n");
    }

    let original_host =
        original_host.context("HTTP request must contain exactly one Host header")?;
    if let Some(client_ip) = client_ip.filter(|value| !value.trim().is_empty()) {
        ensure!(
            !client_ip.contains(['\r', '\n']),
            "client IP contains invalid characters"
        );
        output.extend_from_slice(b"X-Forwarded-For: ");
        output.extend_from_slice(client_ip.as_bytes());
        output.extend_from_slice(b"\r\n");
    }
    output.extend_from_slice(b"X-Forwarded-Proto: ");
    output.extend_from_slice(scheme.as_bytes());
    output.extend_from_slice(b"\r\nX-Forwarded-Host: ");
    output.extend_from_slice(&original_host);
    output.extend_from_slice(b"\r\n");
    if !has_accept_encoding {
        output.extend_from_slice(b"Accept-Encoding: gzip\r\n");
    }
    output.extend_from_slice(b"\r\n");
    output.extend_from_slice(&bytes[header_end + 4..]);
    Ok(output)
}

#[cfg(test)]
fn bearer_token(bytes: &[u8]) -> anyhow::Result<&str> {
    let mut headers = [httparse::EMPTY_HEADER; MAX_HTTP_HEADERS];
    let mut request = httparse::Request::new(&mut headers);
    ensure!(
        request
            .parse(bytes)
            .context("parse HTTP request")?
            .is_complete(),
        "incomplete HTTP request headers"
    );
    let mut value = None;
    for header in request.headers.iter() {
        if header.name.eq_ignore_ascii_case("authorization") {
            ensure!(
                value.is_none(),
                "multiple Authorization headers are not accepted"
            );
            value = Some(
                std::str::from_utf8(header.value).context("Authorization header is not UTF-8")?,
            );
        }
    }
    let value = value.ok_or_else(|| anyhow!("Authorization header is required"))?;
    let (scheme, token) = value
        .trim()
        .split_once(' ')
        .ok_or_else(|| anyhow!("Authorization header must use Bearer"))?;
    ensure!(
        scheme.eq_ignore_ascii_case("Bearer") && !token.trim().is_empty(),
        "Authorization header must use Bearer"
    );
    Ok(token.trim())
}

#[cfg(test)]
fn strip_authorization_header(bytes: &[u8]) -> anyhow::Result<Vec<u8>> {
    let header_end = bytes
        .windows(4)
        .position(|window| window == b"\r\n\r\n")
        .ok_or_else(|| anyhow!("incomplete HTTP request headers"))?;
    let mut output = Vec::with_capacity(bytes.len());
    for (index, line) in bytes[..header_end].split(|byte| *byte == b'\n').enumerate() {
        let line = line.strip_suffix(b"\r").unwrap_or(line);
        let is_authorization = index > 0
            && line
                .splitn(2, |byte| *byte == b':')
                .next()
                .is_some_and(|name| name.eq_ignore_ascii_case(b"authorization"));
        if !is_authorization {
            output.extend_from_slice(line);
            output.extend_from_slice(b"\r\n");
        }
    }
    output.extend_from_slice(b"\r\n");
    output.extend_from_slice(&bytes[header_end + 4..]);
    Ok(output)
}

fn claim_strings<'a>(
    claims: &'a Value,
    path: &str,
) -> anyhow::Result<std::collections::HashSet<&'a str>> {
    let mut value = claims;
    for component in path.split('.') {
        ensure!(
            !component.is_empty(),
            "roles_claim contains an empty path component"
        );
        value = value
            .get(component)
            .ok_or_else(|| anyhow!("JWT role claim is missing"))?;
    }
    let mut values = std::collections::HashSet::new();
    match value {
        Value::String(role) => {
            values.insert(role.as_str());
        }
        Value::Array(roles) => {
            for role in roles {
                values.insert(
                    role.as_str()
                        .ok_or_else(|| anyhow!("JWT role claim array must contain strings"))?,
                );
            }
        }
        _ => bail!("JWT role claim must be a string or string array"),
    }
    Ok(values)
}

fn validate_roles(claims: &Value, config: &ClientAuthorizationConfig) -> Result<(), Denial> {
    if config.required_roles.is_empty() {
        return Ok(());
    }
    let roles = claim_strings(claims, &config.roles_claim).map_err(Denial::Forbidden)?;
    let role_ok = match config.role_match {
        RoleMatch::Any => config
            .required_roles
            .iter()
            .any(|required| roles.contains(required.as_str())),
        RoleMatch::All => config
            .required_roles
            .iter()
            .all(|required| roles.contains(required.as_str())),
    };
    if !role_ok {
        return Err(Denial::Forbidden(anyhow!("required JWT role is missing")));
    }
    Ok(())
}

fn identity_from_claims(
    claims: &Value,
    roles_claim: &str,
) -> anyhow::Result<AuthenticatedIdentity> {
    let subject = claims
        .get("sub")
        .and_then(Value::as_str)
        .context("identity token has no string sub claim")?
        .to_string();
    let email = claims
        .get("email")
        .and_then(Value::as_str)
        .map(str::to_string);
    let name = claims
        .get("name")
        .and_then(Value::as_str)
        .map(str::to_string);
    let username = ["preferred_username", "name"]
        .into_iter()
        .find_map(|name| claims.get(name).and_then(Value::as_str))
        .map(str::to_string)
        .or_else(|| email.clone())
        .unwrap_or_else(|| subject.clone());
    let mut groups = claim_strings(claims, roles_claim)
        .map(|values| values.into_iter().map(str::to_string).collect::<Vec<_>>())
        .or_else(|_| {
            claims
                .get("groups")
                .map(claim_value_strings)
                .transpose()
                .map(Option::unwrap_or_default)
        })?;
    groups.sort();
    let expires_unix = claims
        .get("exp")
        .and_then(Value::as_u64)
        .unwrap_or_default();
    for value in std::iter::once(subject.as_str())
        .chain(std::iter::once(username.as_str()))
        .chain(name.iter().map(String::as_str))
        .chain(email.iter().map(String::as_str))
        .chain(groups.iter().map(String::as_str))
    {
        ensure!(
            !value.contains(['\r', '\n']),
            "identity claim contains a newline"
        );
    }
    Ok(AuthenticatedIdentity {
        subject,
        username,
        name,
        email,
        groups,
        expires_unix,
    })
}

fn claim_value_strings(value: &Value) -> anyhow::Result<Vec<String>> {
    match value {
        Value::String(value) => Ok(vec![value.clone()]),
        Value::Array(values) => values
            .iter()
            .map(|value| {
                value
                    .as_str()
                    .map(str::to_string)
                    .context("identity claim array must contain strings")
            })
            .collect(),
        _ => bail!("identity claim must be a string or string array"),
    }
}

fn decode_verified_claims(token: &str) -> anyhow::Result<Value> {
    let payload = token
        .split('.')
        .nth(1)
        .context("verified ID token has no payload")?;
    let bytes = URL_SAFE_NO_PAD
        .decode(payload)
        .context("decode verified ID token payload")?;
    serde_json::from_slice(&bytes).context("decode verified ID token claims")
}

fn request_cookie(headers: &HeaderMap, name: &str) -> Option<String> {
    headers
        .get_all(header::COOKIE)
        .iter()
        .filter_map(|value| value.to_str().ok())
        .flat_map(|value| value.split(';'))
        .filter_map(|pair| pair.trim().split_once('='))
        .find_map(|(candidate, value)| (candidate == name).then(|| value.to_string()))
}

fn safe_return_to(uri: &Uri) -> String {
    let value = uri
        .path_and_query()
        .map(|value| value.as_str())
        .unwrap_or("/");
    if value.starts_with('/') && !value.starts_with("//") && value.len() <= 1024 {
        value.to_string()
    } else {
        "/".to_string()
    }
}

fn unix_now() -> u64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs()
}

fn load_or_create_cookie_key(path: &Path) -> anyhow::Result<Key> {
    if path.exists() {
        let bytes =
            fs::read(path).with_context(|| format!("read OIDC session key {}", path.display()))?;
        return Key::try_from(bytes.as_slice())
            .context("OIDC session key must contain at least 64 random bytes");
    }
    if let Some(parent) = path
        .parent()
        .filter(|parent| !parent.as_os_str().is_empty())
    {
        fs::create_dir_all(parent)
            .with_context(|| format!("create OIDC session key directory {}", parent.display()))?;
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            fs::set_permissions(parent, fs::Permissions::from_mode(0o700)).with_context(|| {
                format!("restrict OIDC session key directory {}", parent.display())
            })?;
        }
    }
    let key = Key::try_generate().context("operating system random source is unavailable")?;
    let mut file = AtomicWriteFile::open(path)
        .with_context(|| format!("create OIDC session key {}", path.display()))?;
    file.write_all(key.master())
        .with_context(|| format!("write OIDC session key {}", path.display()))?;
    file.commit()
        .with_context(|| format!("commit OIDC session key {}", path.display()))?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        fs::set_permissions(path, fs::Permissions::from_mode(0o600))
            .with_context(|| format!("restrict OIDC session key {}", path.display()))?;
    }
    Ok(key)
}

fn clear_cookie(name: &str) -> String {
    format!("{name}=; Path=/; HttpOnly; SameSite=Lax; Secure; Max-Age=0")
}

fn redirect_response<const N: usize>(
    status: StatusCode,
    location: &str,
    cookies: [String; N],
) -> anyhow::Result<AuthResponse> {
    let mut headers = HeaderMap::new();
    headers.insert(
        header::LOCATION,
        header::HeaderValue::from_str(location).context("invalid redirect location")?,
    );
    headers.insert(
        header::CACHE_CONTROL,
        header::HeaderValue::from_static("no-store"),
    );
    for cookie in cookies {
        headers.append(
            header::SET_COOKIE,
            header::HeaderValue::from_str(&cookie).context("invalid Set-Cookie value")?,
        );
    }
    Ok(AuthResponse {
        status,
        headers,
        body: Bytes::new(),
    })
}

fn json_response(status: StatusCode, body: &'static str) -> AuthResponse {
    let mut headers = HeaderMap::new();
    headers.insert(
        header::CONTENT_TYPE,
        header::HeaderValue::from_static("application/json"),
    );
    headers.insert(
        header::CACHE_CONTROL,
        header::HeaderValue::from_static("no-store"),
    );
    AuthResponse {
        status,
        headers,
        body: Bytes::from_static(body.as_bytes()),
    }
}

fn unauthorized_response() -> AuthResponse {
    let mut response = json_response(StatusCode::UNAUTHORIZED, "{\"error\":\"unauthorized\"}\n");
    response.headers.insert(
        header::WWW_AUTHENTICATE,
        header::HeaderValue::from_static("Bearer realm=\"lfp-pipe\""),
    );
    response
}

fn forbidden_response() -> AuthResponse {
    json_response(StatusCode::FORBIDDEN, "{\"error\":\"forbidden\"}\n")
}

fn internal_error_response() -> AuthResponse {
    json_response(
        StatusCode::INTERNAL_SERVER_ERROR,
        "{\"error\":\"authentication unavailable\"}\n",
    )
}

fn method_not_allowed_response() -> AuthResponse {
    json_response(
        StatusCode::METHOD_NOT_ALLOWED,
        "{\"error\":\"method not allowed\"}\n",
    )
}

#[cfg(test)]
mod tests {
    use super::{
        bearer_token, claim_strings, decode_verified_claims, identity_from_claims, request_path,
        safe_return_to, set_host_header, set_proxy_headers, strip_authorization_header,
        strip_request_path_prefix,
    };
    use base64::{Engine, engine::general_purpose::URL_SAFE_NO_PAD};
    use hyper::Uri;
    use serde_json::json;

    #[test]
    fn parses_bearer_header_case_insensitively() {
        let request = b"POST /api/jobs HTTP/1.1\r\nHost: service.example\r\nauthorization: bearer abc.def.ghi\r\n\r\n";
        assert_eq!(bearer_token(request).expect("bearer"), "abc.def.ghi");
    }

    #[test]
    fn reads_nested_string_role_claims() {
        let claims = json!({"realm_access": {"roles": ["service-user", "admin"]}});
        let roles = claim_strings(&claims, "realm_access.roles").expect("roles");
        assert!(roles.contains("service-user"));
    }

    #[test]
    fn verified_oidc_claims_keep_nested_roles_for_forwarding() {
        let claims = json!({
            "sub": "user-1",
            "preferred_username": "reggie",
            "email": "reggie@example.com",
            "realm_access": {"roles": ["operators", "admins"]}
        });
        let token = format!(
            "header.{}.signature",
            URL_SAFE_NO_PAD.encode(serde_json::to_vec(&claims).expect("claims"))
        );
        let decoded = decode_verified_claims(&token).expect("decoded claims");
        let identity = identity_from_claims(&decoded, "realm_access.roles").expect("identity");
        assert_eq!(identity.username, "reggie");
        assert_eq!(identity.groups, ["admins", "operators"]);
    }

    #[test]
    fn oidc_return_target_is_same_origin_and_bounded() {
        let safe: Uri = "/dashboard?tab=jobs".parse().expect("safe URI");
        assert_eq!(safe_return_to(&safe), "/dashboard?tab=jobs");
        let unsafe_target: Uri = "//attacker.example/path".parse().expect("URI");
        assert_eq!(safe_return_to(&unsafe_target), "/");
    }

    #[test]
    fn rewrites_host_header_and_preserves_body() {
        let request =
            b"POST /api/generate HTTP/1.1\r\nhost: public.example\r\nContent-Length: 2\r\n\r\n{}"
                .to_vec();
        let rewritten = set_host_header(request, "127.0.0.1:11434").expect("host rewrite");
        assert_eq!(
            rewritten,
            b"POST /api/generate HTTP/1.1\r\nHost: 127.0.0.1:11434\r\nContent-Length: 2\r\n\r\n{}"
        );
    }

    #[test]
    fn removes_bearer_token_before_forwarding() {
        let request = b"POST /api/jobs HTTP/1.1\r\nHost: service.example\r\nAuthorization: Bearer secret\r\nContent-Length: 2\r\n\r\n{}";
        let stripped = strip_authorization_header(request).expect("stripped request");
        assert!(
            !stripped
                .windows(b"secret".len())
                .any(|value| value == b"secret")
        );
        assert!(stripped.ends_with(b"\r\n\r\n{}"));
    }

    #[test]
    fn strips_routing_prefix_and_preserves_query_and_body() {
        let request = b"POST /gateway/api/jobs?stream=false HTTP/1.1\r\nHost: service.example\r\nContent-Length: 2\r\n\r\n{}".to_vec();
        assert_eq!(request_path(&request).expect("path"), "/gateway/api/jobs");
        let rewritten = strip_request_path_prefix(request, "/gateway").expect("rewritten");
        assert!(rewritten.starts_with(b"POST /api/jobs?stream=false HTTP/1.1\r\n"));
        assert!(rewritten.ends_with(b"\r\n\r\n{}"));
    }

    #[test]
    fn proxy_headers_replace_spoofed_values_and_preserve_public_host() {
        let request = b"POST /xyz/api?stream=false HTTP/1.1\r\nHost: public.example:443\r\nX-Forwarded-For: 203.0.113.99\r\nX-Forwarded-Proto: ftp\r\nX-Forwarded-Host: attacker.example\r\nContent-Length: 2\r\n\r\n{}".to_vec();
        let rewritten =
            set_proxy_headers(request, Some("198.51.100.24"), "https").expect("proxy headers");
        let text = String::from_utf8(rewritten).expect("UTF-8 request");
        assert!(text.starts_with("POST /xyz/api?stream=false HTTP/1.1\r\n"));
        assert!(text.contains("Host: public.example:443\r\n"));
        assert!(text.contains("X-Forwarded-For: 198.51.100.24\r\n"));
        assert!(text.contains("X-Forwarded-Proto: https\r\n"));
        assert!(text.contains("X-Forwarded-Host: public.example:443\r\n"));
        assert!(text.contains("Accept-Encoding: gzip\r\n"));
        assert!(!text.contains("attacker.example"));
        assert!(!text.contains("203.0.113.99"));
        assert!(text.ends_with("\r\n\r\n{}"));
    }

    #[test]
    fn proxy_headers_preserve_existing_accept_encoding() {
        let request =
            b"GET / HTTP/1.1\r\nHost: public.example\r\nAccept-Encoding: br\r\n\r\n".to_vec();
        let rewritten = set_proxy_headers(request, None, "http").expect("proxy headers");
        let text = String::from_utf8(rewritten).expect("UTF-8 request");
        assert_eq!(text.matches("Accept-Encoding:").count(), 1);
        assert!(text.contains("Accept-Encoding: br\r\n"));
    }

    #[test]
    fn host_override_keeps_original_host_in_forwarding_header() {
        let request = b"GET / HTTP/1.1\r\nHost: public.example\r\n\r\n".to_vec();
        let forwarded =
            set_proxy_headers(request, Some("198.51.100.24"), "https").expect("proxy headers");
        let rewritten = set_host_header(forwarded, "127.0.0.1:8080").expect("host override");
        let text = String::from_utf8(rewritten).expect("UTF-8 request");
        assert!(text.contains("Host: 127.0.0.1:8080\r\n"));
        assert!(text.contains("X-Forwarded-Host: public.example\r\n"));
    }
}
