[workspace]
members = ["client", "server", "shared"]
resolver = "2"

[workspace.package]
edition = "2024"
version = "0.1.12"

[workspace.dependencies]
anyhow = "1.0"
atomic-write-file = "0.3.1"
auto-launcher = "1.1.0"
async-nats = { version = "0.44", features = ["websockets"] }
base64 = "0.22"
bytes = "1.10"
clap = { version = "4.5", features = ["derive", "env"] }
clienthello = { version = "0.1.3", features = ["std", "full"] }
dirs = "6.0.0"
futures = "0.3"
httparse = "1.10"
jsonwebtoken = { version = "11.0", default-features = false, features = ["rust_crypto"] }
notify = "8.2.0"
reqwest = { version = "0.13.4", default-features = false, features = ["rustls-no-provider", "form", "json", "stream"] }
rustls = { version = "0.23", default-features = false, features = ["ring", "std", "tls12"] }
rustls-acme = { version = "0.15.4", default-features = false, features = ["ring", "tls12", "tokio", "webpki-roots"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.48", features = ["full"] }
tokio-stream = "0.1"
toml = "0.9"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
tray-icon = "0.24.2"
tiny-skia = "0.11.4"
tinyfiledialogs = "3.9.1"
winit = "0.30.13"
open = "5.4.1"
tokio-splice2 = "0.3.2"
url = "2.5"
uuid = { version = "1.18", features = ["serde", "v4"] }
