[package]
name = "server"
version = "0.1.0"
edition = "2024"
autobins = false

[lib]
name = "server"

[[bin]]
name = "lfp-pipe-server"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
async-nats.workspace = true
clap.workspace = true
futures.workspace = true
shared = { path = "../shared" }
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true
