server_name: $HOSTNAME
port: 4222

cluster {
  name: lfp-connect
  port: 6222
  routes: [nats://tasks.nats:6222]
  connect_retries: 30
  connect_backoff: true
}

accounts {
  AUTH: {
    users: [
      { user: "auth-svc", password: $NATS_CALLOUT_PASSWORD }
    ]
  }
  TUNNELS: {}
  SYS: {
    users: [
      { user: "system", password: $NATS_SYSTEM_PASSWORD }
    ]
  }
}

system_account: SYS

authorization {
  timeout: 1s
  auth_callout {
    account: AUTH
    auth_users: [auth-svc]
    issuer: $NATS_AUTH_ISSUER_PUBLIC_KEY
    xkey: $NATS_AUTH_XKEY_PUBLIC_KEY
  }
}

http: 8222
